/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class frmHistorialTickets extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmHistorialTickets.class.getName());

    /**
     * Creates new form frmHistorialTickets
     */
    public frmHistorialTickets() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null); // Centrar
        cargarListaTickets();
    }
    
    public void cargarListaTickets() {
    DefaultListModel<String> modeloLista = new DefaultListModel<>();
    File carpetaProyecto = new File("."); 
    
    // Filtro para archivos de ticket
    File[] archivos = carpetaProyecto.listFiles((dir, nombre) -> 
        nombre.startsWith("Ticket_") && nombre.endsWith(".txt")
    );

    if (archivos != null && archivos.length > 0) {
        for (File archivo : archivos) {
            modeloLista.addElement(archivo.getName());
        }
    } else {
        modeloLista.addElement("No hay tickets generados");
    }
    listArchivos.setModel(modeloLista);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listArchivos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContenidoTicket = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jScrollPane1.setBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tickets Generados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 0, 24))); // NOI18N

        listArchivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listArchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listArchivosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listArchivos);

        txtContenidoTicket.setEditable(false);
        txtContenidoTicket.setBackground(new java.awt.Color(255, 255, 255));
        txtContenidoTicket.setColumns(20);
        txtContenidoTicket.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtContenidoTicket.setRows(5);
        txtContenidoTicket.setWrapStyleWord(true);
        txtContenidoTicket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(txtContenidoTicket);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmPrincipal ventanaPrincipal = new frmPrincipal();
           ventanaPrincipal.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void listArchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listArchivosValueChanged
        // Evita que el código se ejecute dos veces (al presionar y al soltar)
    if (!evt.getValueIsAdjusting()) {
        String archivoSeleccionado = listArchivos.getSelectedValue();
        
        if (archivoSeleccionado != null && !archivoSeleccionado.equals("No hay tickets generados")) {
            try {
                // Usamos File para asegurarnos de que la ruta es relativa a la raíz
                File archivo = new File(archivoSeleccionado);
                
                // Leemos todas las líneas y las unimos con saltos de línea
                String contenido = new String(java.nio.file.Files.readAllBytes(archivo.toPath()));
                
                txtContenidoTicket.setText(contenido);
                txtContenidoTicket.setCaretPosition(0); // Scroll al inicio
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage());
            }
        }
    }
    }//GEN-LAST:event_listArchivosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmHistorialTickets().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listArchivos;
    private javax.swing.JTextArea txtContenidoTicket;
    // End of variables declaration//GEN-END:variables
}
