/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorReserva;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Reserva;


public class frmReservas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmReservas.class.getName());

    /**
     * Creates new form frmMisReservas
     */
    public frmReservas() {
        initComponents();
    }
    
    
    public void actualizarTabla() {
    // 1. Definir los títulos de las columnas
    String[] columnas = {"DNI Pasajero", "Vuelo Ida", "Vuelo Vuelta", "Asientos", "Total"};
    
    // 2. Crear el modelo de la tabla (no editable para el usuario)
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    // 3. Obtener las reservas desde tu controlador (usando tu estructura de paquetes)
    // Asumiendo que ControladorReservas tiene una lista de todas las reservas
    List<Reserva> lista = ControladorReserva.getInstancia().getListaReservas();

    // 4. Llenar el modelo con los datos de tu clase Reserva
    for (Reserva r : lista) {
        Object[] fila = {
            r.getDniPasajero(),
            (r.getVueloIda() != null) ? r.getVueloIda().getOrigen() + "-" + r.getVueloIda().getDestino() : "N/A",
            (r.getVueloVuelta() != null) ? r.getVueloVuelta().getOrigen() + "-" + r.getVueloVuelta().getDestino() : "N/A",
            "Ida: " + r.getResumenAsientos(r.getAsientosIda()), // Usamos tu nuevo método
            String.format("$%.2f", r.getTotalPagar())
        };
        modelo.addRow(fila);
    }

    // 5. Aplicar el modelo a la tabla de la interfaz
    tblReservas.setModel(modelo);
}
    public void cargarTablaReservas() {
    // Definimos los títulos de forma manual
    String[] titulos = {"DNI Pasajero", "Vuelo", "Asientos Ida", "Asientos Vuelta"};
    
    // Creamos el modelo con esos títulos y 0 filas iniciales
    DefaultTableModel modelo = new DefaultTableModel(titulos, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Esto hace que la tabla sea solo de lectura
        }
    };

    // Obtenemos las reservas del controlador
    for (modelo.Reserva r : controlador.ControladorReserva.getInstancia().getListaReservas()) {
        Object[] fila = {
            r.getDniPasajero(),
            r.getResumenAsientos(r.getAsientosIda()),
            r.getResumenAsientos(r.getAsientosVuelta()),
            String.format("$%.2f", r.getTotalPagar())
        };
        modelo.addRow(fila);
    }
    // 4. Asignar el modelo a la tabla
    this.tblReservas.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        btnRegresarPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI / Pasajero", "Vuelo", "Asientos Ida", "Asientos Vuelta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReservas);

        btnRegresarPrincipal.setText("Regresar ");
        btnRegresarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnRegresarPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(btnRegresarPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPrincipalActionPerformed
        frmPrincipal ventanaPrincipal = new frmPrincipal();
        ventanaPrincipal.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnRegresarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmReservas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservas;
    // End of variables declaration//GEN-END:variables
}
